function [options] = compi_ioio_task_options(options)


options.task.design = fullfile(options.roots.config,'COMPI.txt');
design = load(options.task.design);

options.task.cueCodes = [9:14];
options.task.cueProbs = [0.75:-0.10:0.25];
options.task.TrialsperBlock = 17;
options.task.probabilities = [design(1,end),...
    design(1+options.task.TrialsperBlock,end),...
    design(1+2*options.task.TrialsperBlock,end),...
    design(1+3*options.task.TrialsperBlock,end),...
    design(1+4*options.task.TrialsperBlock,end),...
    design(1+5*options.task.TrialsperBlock,end),...
    design(1+6*options.task.TrialsperBlock,end),...
    design(1+7*options.task.TrialsperBlock,end),...
    design(1+8*options.task.TrialsperBlock,end),...
    design(1+9*options.task.TrialsperBlock,end)];
options.task.TrialbyTrialprob       = ...
    [ones(options.task.TrialsperBlock,1).*options.task.probabilities(1);ones(options.task.TrialsperBlock,1).*options.task.probabilities(2);...
    ones(options.task.TrialsperBlock,1).*options.task.probabilities(3);ones(options.task.TrialsperBlock,1).*options.task.probabilities(4);...
    ones(options.task.TrialsperBlock,1).*options.task.probabilities(5); ones(options.task.TrialsperBlock,1).*options.task.probabilities(6);...
    ones(options.task.TrialsperBlock,1).*options.task.probabilities(7);ones(options.task.TrialsperBlock,1).*options.task.probabilities(8);...
    ones(options.task.TrialsperBlock,1).*options.task.probabilities(9);ones(options.task.TrialsperBlock,1).*options.task.probabilities(10)];

options.task.helpful1 = zeros(size(design,1),1);
options.task.helpful1(1:2*options.task.TrialsperBlock,1) = 1; % first 2 blocks are helpful
options.task.stable   = zeros(size(design,1),1);
options.task.stable(1:2*options.task.TrialsperBlock,1) = 1;
options.task.stable(1+8*options.task.TrialsperBlock:end,1) = 1;
options.task.volatile   = zeros(size(design,1),1);
options.task.volatile(1+2*options.task.TrialsperBlock:8*options.task.TrialsperBlock,1) = 1;
options.task.helpful2 = zeros(size(design,1),1);
options.task.helpful2(1+8*options.task.TrialsperBlock:end,1) = 1;

configs = load(fullfile(options.roots.config,'COMPI.txt'));
options.task.vol_struct = configs(:,end);

